server:
  port: 7001
eureka:
  instance:
    hostname: eurake7001.com   #eureka服务器的实例名称
  client:
    register-with-eureka: false  # false表示不向注册中西注册自己
    fetch-registry: false  #false表示自己端就是注册中西，主要责任就是维护服务实例，不需要管其他的事情（检索服务）
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址   查询服务和注册服务都需要依赖这个地址（单机）。







